theme: jekyll-theme-architect
title: Build Cloud-Native App
description: Build modern app using open source, cloud computing, container and serverless technologies, with a working sample app.
show_downloads: "false"